---

- name: provision server
  hosts: all
  become: True
  become_user: root
  vars:
    iptables_allowed_ports:
      - {protocol: tcp, port: 80}
      - {protocol: tcp, port: 443}
      - {protocol: udp, port: 161}
  roles:
    - webserver
  tasks:
    - name: Print message
      debug:
        msg: "Site locates at http://{{ ansible_default_ipv4.address }}/"
