---

- name: provision server
  hosts: all
  become: True
  become_user: root
  vars:
    sshgroup_name: sshusers
    user:
      login: deploy
      password_hash: '$6$NwI7op8FHR1VQta6$zuQXHtNtM/7SRQsf1./18WbBrHMq4mT88nWh67ThmlWcqyVX3FBTY9uj/07tR9ViDEvjg6/bh0y3mSjeDQYe3.'
      authorized_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key'
      group: "{{ sshgroup_name }}"
  tasks:
    - name: wheel group is created
      group: name=wheel state=present

    - name: sshusers group is created
      group:
        name: "{{ sshgroup_name }}"
        state: present

    - name: create admin accounts
      user:
        name: "{{ user.login }}"
        groups: "{{ user.group }}"
        shell: /bin/bash
        update_password: always
        password: "{{ user.password_hash }}"

    - name: super admins can sudo without password
      lineinfile:
        dest: /etc/sudoers
        state: present
        line: "{{ user.login }} ALL=(ALL:ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'

    - name: Set authorized key for deploy user
      authorized_key:
        user: "{{ user.login }}"
        state: present
        key: "{{ user.authorized_key }}"

    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: install git
      yum:
        name: git
        state: present

    - iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 80
        ctstate: NEW
        syn: match
        jump: ACCEPT
        comment: Accept new http connections.

    - name: Httpd is restarted
      systemd:
        name: httpd
        enabled: yes
        state: restarted
        daemon_reload: yes

# Tasks
    # Install snmpd
    - name: Install snmpd
      yum:
        name: net-snmp
        state: present
    
    # Remove default snmpd config via file module 

 # - name: move snmpd config files
   # command: mv /etc/snmp/snmpd.conf /etc/snmp/snmpd.conf.org

    - name: Remove default config
      file:
        path: /etc/snmp/snmpd.conf
        state: absent

    # Configure snmpd via blockinfile module

    - name: Configure snmpd via blockinfile
      blockinfile:
        path: /etc/snmp/snmpd.conf
        create: true
        block: |
          com2sec ConfigUser      default         9VEteky0jjKdnUrap
          com2sec AllUser         default         cae5d4182257cc667
          group   ConfigGroup     v2c             ConfigUser
          group   AllGroup        v2c             AllUser
          view    SystemView      included        .1.3.6.1.2.1.1
          view    SystemView      included        .1.3.6.1.2.1.25.1.1
          view    AllView         included        .1
          access  ConfigGroup     ""      any     noauth  exact   SystemView      none    none
          access  AllGroup        ""      any     noauth  exact   AllView         none    none 

    # Open via iptables module 161 udp port

    - name: Open 161 udp
      iptables:
        chain: INPUT
        protocol: udp
        destination_port: 161 
        jump: ACCEPT
        comment: Open 161th udp port

    # Generate self signed cert via openssl_certificate module

    - name: Install pip
      yum:
        name: python-pip
        state: present

    - name: Install criptography
      pip:
        name: cryptography
        state: latest

    - name: Remove old version of pyOpenSSL
      yum:
        name: pyOpenSSL
        state: absent
 
    - name: Install pyOpenSSL
      pip:
        name: pyOpenSSL
        state: present

    - name: Generate sertificates
      openssl_certificate:
        path: /etc/ssl/certs/my.crt
        privatekey_path: /etc/ssl/certs/my.pem
        csr_path: /etc/ssl/certs/my.csr
        provider: selfsigned

    - name: Print message
      debug:
        msg: "Site locates at http://{{ ansible_default_ipv4.address }}/"
