---

- name: demo playbook
  hosts: all
  tasks:

    - name: set var with all hostnames
      set_fact: all_hosts="{{ groups.all | map('extract', hostvars, ['inventory_hostname']) | join(',') }}"

    - name: show all_hosts
      debug: var=all_hosts

    - name: Magic 8 ball for MUDs
      debug:
        msg: "{{ item }}"
      with_random_choice:
        - "go through the door"
        - "drink from the goblet"
        - "press the red button"
        - "do nothing"
