---

- winmod:
  register: res
  when: ansible_os_family == "Windows"

- bash_mod:

- mymod:
  register: res
  when: ansible_distribution == 'CentOS'

- debug:
    var: res.msg

- name: set var with all acounts without password
  set_fact: mp="{{ super_admins | selectattr('password_hash', 'undefined') | map(attribute='email') | list }}"

- name: set var with all acounts without password // test_plugin
  set_fact: mp="{{ super_admins | select('test_user') | map(attribute='email') | list }}"
