---

- name: provision server
  hosts: all
  become: True
  become_user: root
  vars:
    default_password_hash: '$6$NwI7op8FHR1VQta6$zuQXHtNtM/7SRQsf1./18WbBrHMq4mT88nWh67ThmlWcqyVX3FBTY9uj/07tR9ViDEvjg6/bh0y3mSjeDQYe3.'
    super_admins:
      - login: deploy
        password_hash: "{{ default_password_hash }}"
        email: dep@loy.me
      - login: deploy2
        email: dep@loy.com
    sshgroup_name: sshusers
    iptables_allowed_ports:
      - {protocol: tcp, port: 80}
      - {protocol: tcp, port: 443}
      - {protocol: udp, port: 161}
  handlers:
    - name: reload iptables
      command: iptables-restore /etc/sysconfig/iptables
    - name: reload ip6tables
      command: ip6tables-restore /etc/sysconfig/ip6tables

  tasks:
    - import_tasks: provision_1_users.yml
    - import_tasks: provision_2_software.yml
    - import_tasks: provision_3_iptables.yml
    - import_tasks: provision_4_site.yml
    - import_tasks: provision_5_examples.yml
    - name: Print message
      debug:
        msg: "Site locates at http://{{ ansible_default_ipv4.address }}/"
