---

- name: provision server
  hosts: all
  become: True
  become_user: root
  vars:
    iptables_allowed_ports:
      - {protocol: tcp, port: 80}
  roles:
    - webserver
  tasks:
    - debug:
        var: secret_password
    - debug:
        var: vault_secret_password
    - name: Print message
      debug:
        msg: "Site locates at http://{{ ansible_default_ipv4.address }}/"
