---

- name: provision server
  hosts: all
  become: True
  become_user: root
  vars:
    sshgroup_name: sshusers
    iptables_allowed_ports:
      - {protocol: tcp, port: 80}
    user:
      login: deploy
      password_hash: '$6$NwI7op8FHR1VQta6$zuQXHtNtM/7SRQsf1./18WbBrHMq4mT88nWh67ThmlWcqyVX3FBTY9uj/07tR9ViDEvjg6/bh0y3mSjeDQYe3.'
      authorized_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key'
    v_openssl_root: '/etc/ssl'
    v_openssl_key_folder: "{{ v_openssl_root }}/private"
    v_openssl_cert_folder: "{{ v_openssl_root }}/certs"
    v_openssl_cert_commonname: 'custom_folder'
    v_openssl_privatekey: "{{ v_openssl_key_folder }}/{{ v_openssl_cert_commonname }}.pem"
    v_openssl_csrfile: "{{ v_openssl_cert_folder }}/{{ v_openssl_cert_commonname }}.csr"
    v_openssl_certfile: "{{ v_openssl_cert_folder }}/{{ v_openssl_cert_commonname }}.crt"
  tasks:
    - import_tasks: provision_1_users.yml
    - import_tasks: provision_2_software.yml
    - import_tasks: provision_3_iptables.yml
    - import_tasks: provision_6_snmpd.yml
      vars:
        secret1: secret1
        secret2: secret2
    - import_tasks: provision_7_ssl.yml

    - name: Import playboonk as is
      import_tasks: provision_5_examples_jinja2.yml

    - name: Import playbook with static vars
      import_tasks: provision_5_examples_loops.yml
      vars:
        iptables_allowed_ports:
          # Open via template module & loops ports:
          - {protocol: tcp, port: 180}
          - {protocol: tcp, port: 1443}
          - {protocol: udp, port: 1161}
          - {protocol: udp, port: 161}
          - {protocol: tcp, port: 443}

    - name: Import playbook with dynamic vars
      include_tasks: provision_5_examples_loops.yml
      vars:
       user: "{{ hostvars }}"

    - name: Print message
      debug:
        msg: "Site locates at http://{{ ansible_default_ipv4.address }}/"
